### ISSUE TITLE
Functional question

### ISSUE THREAD

**Issue by haaxema** [bramfoo/solarstats#2]
Hi @bramfoo 

I stumbled on this script, and I have a question.
Your code implies that you can retrieve the serialnumber an Soloadin600.

Is that correct? 

Martin

**Comment by bramfoo** [comment]
Hi Martin,

If I read the code back correctly (having written this more than 7 years ago!) you cannot: on [line 511](https://github.com/bramfoo/solarstats/blob/3d6a30bb6e10fdfb0a8cd25f51ce9a8021952077/solarstats/BLS_MV_Solar_monolithic.py#L511) I write the software version into the serial number parameter for the Soladin600.

It looks a bit confusing because I duplicated the code for both inverters I have, the other one being a Blackline Solar 3000, from which you _can_ read the serial number (see line 443).

Hope this helps!

Cheers,
Bram.

**Comment by haaxema** [comment]
@bramfoo, thanx for the info. It makes sense now.
